export const Country = [
  {
    id: 1,
    name: "afghanistan",
    img: require("../assets/images/Flags/afghanistan.png"),
    code: "93",
  },
  {
    id: 2,
    name: "south africa",
    img: require("../assets/images/Flags/africa.png"),
    code: "27",
  },
  {
    id: 3,
    name: "albania",
    img: require("../assets/images/Flags/albania.png"),
    code: "355",
  },
  {
    id: 4,
    name: "algeria",
    img: require("../assets/images/Flags/algeria.png"),
    code: "213",
  },
  {
    id: 5,
    name: "argentina",
    img: require("../assets/images/Flags/argentina.png"),
    code: "54",
  },
  {
    id: 6,
    name: "australia",
    img: require("../assets/images/Flags/australia.png"),
    code: "61",
  },
  {
    id: 7,
    name: "bahrain",
    img: require("../assets/images/Flags/bahrain.png"),
    code: "973",
  },
  {
    id: 8,
    name: "bangladesh",
    img: require("../assets/images/Flags/bangladesh.png"),
    code: "880",
  },
  {
    id: 9,
    name: "belgium",
    img: require("../assets/images/Flags/belgium.png"),
    code: "32",
  },
  {
    id: 10,
    name: "bosnia",
    img: require("../assets/images/Flags/bosnia.png"),
    code: "387",
  },
  {
    id: 11,
    name: "canada",
    img: require("../assets/images/Flags/canada.png"),
    code: "1",
  },
  {
    id: 12,
    name: "chile",
    img: require("../assets/images/Flags/chile.png"),
    code: "56",
  },
  {
    id: 13,
    name: "china",
    img: require("../assets/images/Flags/china.png"),
    code: "86",
  },
  {
    id: 14,
    name: "colombia",
    img: require("../assets/images/Flags/colombia.png"),
    code: "57",
  },
  {
    id: 15,
    name: "cote de ivore",
    img: require("../assets/images/Flags/cote.png"),
    code: "225",
  },
  {
    id: 16,
    name: "croatia",
    img: require("../assets/images/Flags/croatia.png"),
    code: "385",
  },
  {
    id: 17,
    name: "czech republic",
    img: require("../assets/images/Flags/czech.png"),
    code: "420",
  },
  {
    id: 18,
    name: "denmark",
    img: require("../assets/images/Flags/denmark.png"),
    code: "45",
  },
  {
    id: 19,
    name: "ecuador",
    img: require("../assets/images/Flags/ecuador.png"),
    code: "593",
  },
  {
    id: 20,
    name: "egypt",
    img: require("../assets/images/Flags/egypt.png"),
    code: "20",
  },
  {
    name: "fiji",
    img: require("../assets/images/Flags/fiji.png"),
    code: "679",
    id: 21,
  },
  {
    name: "finland",
    img: require("../assets/images/Flags/finland.png"),
    code: "358",
    id: 22,
  },
  {
    name: "france",
    img: require("../assets/images/Flags/france.png"),
    code: "33",
    id: 23,
  },
  {
    name: "georgia",
    img: require("../assets/images/Flags/georgia.png"),
    code: "995",
    id: 24,
  },
  {
    name: "germany",
    img: require("../assets/images/Flags/germany.png"),
    code: "49",
    id: 25,
  },
  {
    name: "ghana",
    img: require("../assets/images/Flags/ghana.png"),
    code: "233",
    id: 26,
  },
  {
    name: "honduras",
    img: require("../assets/images/Flags/honduras.png"),
    code: "504",
    id: 27,
  },
  {
    name: "hungary",
    img: require("../assets/images/Flags/hungary.png"),
    code: "36",
    id: 28,
  },
  {
    name: "iceland",
    img: require("../assets/images/Flags/iceland.png"),
    code: "354",
    id: 29,
  },
  {
    name: "india",
    img: require("../assets/images/Flags/india.png"),
    code: "91",
    id: 30,
  },
  {
    name: "indonesia",
    img: require("../assets/images/Flags/indonesia.png"),
    code: "62",
    id: 31,
  },
  {
    name: "iran",
    img: require("../assets/images/Flags/iran.png"),
    code: "98",
    id: 32,
  },
  {
    name: "iraq",
    img: require("../assets/images/Flags/iraq.png"),
    code: "964",
    id: 33,
  },
  {
    name: "ireland",
    img: require("../assets/images/Flags/ireland.png"),
    code: "353",
    id: 34,
  },
  {
    name: "italy",
    img: require("../assets/images/Flags/italy.png"),
    code: "39",
    id: 35,
  },
  {
    name: "jamaica",
    img: require("../assets/images/Flags/jamaica.png"),
    code: "1",
    id: 36,
  },
  {
    name: "japan",
    img: require("../assets/images/Flags/japan.png"),
    code: "81",
    id: 37,
  },
  {
    name: "jordan",
    img: require("../assets/images/Flags/jordan.png"),
    code: "962",
    id: 38,
  },
  {
    name: "kenya",
    img: require("../assets/images/Flags/kenya.png"),
    code: "254",
    id: 39,
  },
  {
    name: "kuwait",
    img: require("../assets/images/Flags/kuwait.png"),
    code: "965",
    id: 40,
  },
  {
    name: "lebanon",
    img: require("../assets/images/Flags/lebanon.png"),
    code: "961",
    id: 41,
  },
  {
    name: "libya",
    img: require("../assets/images/Flags/libya.png"),
    code: "218",
    id: 42,
  },
  {
    name: "malaysia",
    img: require("../assets/images/Flags/malaysia.png"),
    code: "60",
    id: 43,
  },
  {
    name: "maldives",
    img: require("../assets/images/Flags/maldives.png"),
    code: "960",
    id: 44,
  },
  {
    name: "mexico",
    img: require("../assets/images/Flags/mexico.png"),
    code: "52",
    id: 45,
  },
  {
    name: "morocco",
    img: require("../assets/images/Flags/morocco.png"),
    code: "212",
    id: 46,
  },
  {
    name: "myanmar",
    img: require("../assets/images/Flags/myanmar.png"),
    code: "95",
    id: 47,
  },
  {
    name: "nepal",
    img: require("../assets/images/Flags/nepal.png"),
    code: "977",
    id: 48,
  },
  {
    name: "netherlands",
    img: require("../assets/images/Flags/netherlands.png"),
    code: "31",
    id: 49,
  },
  {
    name: "nigeria",
    img: require("../assets/images/Flags/nigeria.png"),
    code: "234",
    id: 50,
  },
  {
    name: "pakistan",
    img: require("../assets/images/Flags/pakistan.png"),
    code: "92",
    id: 51,
  },
  {
    name: "paraguay",
    img: require("../assets/images/Flags/paraguay.png"),
    code: "595",
    id: 52,
  },
  {
    name: "peru",
    img: require("../assets/images/Flags/peru.png"),
    code: "51",
    id: 53,
  },
  {
    name: "philippines",
    img: require("../assets/images/Flags/philippines.png"),
    code: "63",
    id: 54,
  },
  {
    name: "poland",
    img: require("../assets/images/Flags/poland.png"),
    code: "48",
    id: 55,
  },
  {
    name: "portugal",
    img: require("../assets/images/Flags/portugal.png"),
    code: "351",
    id: 56,
  },
  {
    name: "qatar",
    img: require("../assets/images/Flags/qatar.png"),
    code: "974",
    id: 57,
  },
  {
    name: "romania",
    img: require("../assets/images/Flags/romania.png"),
    code: "40",
    id: 58,
  },
  {
    name: "russia",
    img: require("../assets/images/Flags/russia.png"),
    code: "7",
    id: 59,
  },
  {
    name: "saudi arabia",
    img: require("../assets/images/Flags/saudi.png"),
    code: "966",
    id: 60,
  },
  {
    name: "scotland",
    img: require("../assets/images/Flags/scotland.png"),
    code: "44",
    id: 61,
  },
  {
    name: "senegal",
    img: require("../assets/images/Flags/senegal.png"),
    code: "221",
    id: 62,
  },
  {
    name: "serbia",
    img: require("../assets/images/Flags/serbia.png"),
    code: "381",
    id: 63,
  },
  {
    name: "singapore",
    img: require("../assets/images/Flags/singapore.png"),
    code: "65",
    id: 64,
  },
  {
    name: "slovakia",
    img: require("../assets/images/Flags/slovakia.png"),
    code: "421",
    id: 65,
  },
  {
    name: "slovenia",
    img: require("../assets/images/Flags/slovenia.png"),
    code: "386",
    id: 66,
  },
  {
    name: "south korea",
    img: require("../assets/images/Flags/south.png"),
    code: "82",
    id: 67,
  },
  {
    name: "spain",
    img: require("../assets/images/Flags/spain.png"),
    code: "34",
    id: 68,
  },
  {
    name: "sri lanka",
    img: require("../assets/images/Flags/sri.png"),
    code: "94",
    id: 69,
  },
  {
    name: "sweden",
    img: require("../assets/images/Flags/sweden.png"),
    code: "46",
    id: 70,
  },
  {
    name: "switzerland",
    img: require("../assets/images/Flags/switzerland.png"),
    code: "41",
    id: 71,
  },
  {
    name: "syria",
    img: require("../assets/images/Flags/syria.png"),
    code: "963",
    id: 72,
  },
  {
    name: "turkey",
    img: require("../assets/images/Flags/turkey.png"),
    code: "90",
    id: 73,
  },
  {
    name: "UAE",
    img: require("../assets/images/Flags/UAE.png"),
    code: "971",
    id: 74,
  },
  {
    name: "UK",
    img: require("../assets/images/Flags/UK.png"),
    code: "44",
    id: 75,
  },
  {
    name: "US",
    img: require("../assets/images/Flags/US.png"),
    code: "1",
    id: 76,
  },
  {
    name: "uruguay",
    img: require("../assets/images/Flags/uruguay.png"),
    code: "598",
    id: 77,
  },
  {
    name: "wales",
    img: require("../assets/images/Flags/wales.png"),
    code: "44",
    id: 78,
  },
  {
    name: "yemen",
    img: require("../assets/images/Flags/yemen.png"),
    code: "967",
    id: 79,
  },
  {
    name: "zimbabwe",
    img: require("../assets/images/Flags/zimbabwe.png"),
    code: "263",
    id: 80,
  },
];
