export const Posts = [
  {
    profileimg: require("../assets/images/profile.jpg"),
    name: "Mohamed Nawaz",
    location: "Colombo, Sri Lanka",
    post: "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly.",
    postimg: require("../assets/images/img04.jpg"),
    likes: "1.1k",
    comments: "283",
    share: "28",
    liked: false,
  },
  {
    profileimg: require("../assets/images/cover.jpg"),
    name: "Keerthi Suresh",
    location: "Chennai, India",
    post: "",
    postimg: require("../assets/images/img03.jpg"),
    likes: "480",
    comments: "38",
    share: "5",
    liked: true,
  },
  {
    profileimg: require("../assets/images/img04.jpg"),
    name: "Kevin Max",
    location: "Madrid, Spain",
    post: "Particular unaffected projection sentiments no my. Music marry as at cause party worth weeks.",
    postimg: require("../assets/images/img01.jpg"),
    likes: "122",
    comments: "9",
    share: "0",
    liked: true,
  },
  {
    profileimg: require("../assets/images/img02.jpg"),
    name: "Emma Harper",
    location: "Quebec, Canada",
    post: "shy shade",
    postimg: require("../assets/images/cover.jpg"),
    likes: "2k",
    comments: "791",
    share: "13",
    liked: false,
  },
  {
    profileimg: require("../assets/images/img01.jpg"),
    name: "Joe Allen",
    location: "New South Wales, Australia",
    post: "In alteration insipidity impression by travelling reasonable up motionless.",
    postimg: "",
    likes: "588",
    comments: "43",
    share: "2",
    liked: true,
  },
];
